KERNEL_IMAGETYPES = "fitImage"
KERNEL_CLASSES += "kernel-fitimage"
IMAGE_FSTYPES = " ostreepush garagesign garagecheck ota-ext4 ostree.tar.bz2 ota.tar.xz wic" 
# ostreepush garagesign garagecheck ota-ext4 ostree.tar.bz2 ota.tar.xz wic"
OSTREE_KERNEL = "fitImage-${INITRAMFS_IMAGE}-${MACHINE}-${MACHINE}"
OSTREE_KERNEL_ARGS = "console=ttymxc1,115200 ramdisk_size=2048 root=/dev/ram0 rw rootfstype=ext4 ostree_root=/dev/mmcblk1p2"

# WKS_FILE:sota = "sdimage-imx8-sota.wks.in"
WKS_FILE = "sdimage-imx8-sota.wks.in"
IMAGE_BOOT_FILES = "imx8mp-icore_boot.scr"